site_name: XNET Docs
site_url: https://xnet.company

theme:
  logo: /stylesheets/logo.webp
  #logo: https://www.xnet.company/favicon.ico
  favicon: /stylesheets/logo.webp
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.highlight
    - header.autohide
    - content.code.copy
    - navigation.footer
  hide:
    - toc
  icon:
    admonition:
      info: fontawesome/solid/circle-info
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  homepage: https://www.xnet.company/
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/xnetmobile
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/XNET_mobile
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCyIptNxGEgzXpckV5EL38qQ
  nav:
    - "Custom Link 1": https://example.com
    - "Custom Link 2": https://anotherexample.com
    - "GitHub": https://github.com/your-repo

copyright: "Copyright © 2024 XNET Inc."

plugins:
  - search:
      lang: en

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

nav: 
  - Overview:
    - XNET Vision: 'overview.md'
    - Build the Network: 'build.md'
    - Charter: 'charter.md'
  - Token: 
    - The XNET Token: 'token.md'
    - Claiming Rewards: 'distribution.md'
  - Migration:
    - Solana Migration, Part 1: 'migration.md'
    - Solana Migration, Part 2: 'migration_part_2.md'
  - Technical Docs:
    - Carrier WiFi Offload: 'offload.md'
    - WiFi Reactivation: 'reactivation.md'
    - Datasheets: 'datasheet.md'
    - Archive: 'archive.md'
  - '<span class="xnet-home-link">XNET Home</span>': https://xnet.company

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
